# Configuraciones del servidor
server:
  port: 9090

# Configuraciones de spring cloud
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/parcialBackEnd
        registration:
          keycloak-provider:
            client-id: api-gateway-client
            client-secret: NXw6whIQW356MVZQHxHXBMVNcUnerYAH
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bills
          uri: http://localhost:8081
          predicates:
            - Path= /api/v1/**
          filters:
            - StripPrefix=2

# Configuraciones de eureka
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka